# See example script at https://github.com/JuliaLang/Example.jl
# Also see Travis script https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/julia.rb

language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false

codecov: true

coveralls: true

#jobs:
#  include:
#    - stage: "Documentation"
#      julia: 1.0
#      os: linux
#      script:
#        - julia --project=docs/ -e 'using Pkg;
#                                    Pkg.develop(PackageSpec(path=pwd()));
#                                    Pkg.build("LinearInterpolators");
#                                    Pkg.instantiate()'
#        - julia --project=docs/ docs/make.jl
#      after_success: skip
